package com.jmack.Base;


public class GlobalConstants {

	protected String testDataFileName = "TestParametersJSON.json";
	protected String testReferenceFileName = "testReference.properties";
	
	protected String testDataFilePath = System.getProperty("user.dir")+"\\src\\test\\resources\\"+testDataFileName;
	protected String testReferenceFilePath = System.getProperty("user.dir")+"\\src\\test\\resources\\"+testReferenceFileName;
	
	protected String locatorSeparator = "@@@";
	protected String compoundLocatorPlacehold = "~~~";
	
	protected String perfectoSecurityToken = "eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIwNjgzYTliOC1lOTU2LTQ2MTQtYTJmYS0xNzU1ODI1NjY4M2UiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNTIwMjg1NTA3LCJpc3MiOiJodHRwczovL2F1dGgucGVyZmVjdG9tb2JpbGUuY29tL2F1dGgvcmVhbG1zL2libWdicy1wZXJmZWN0b21vYmlsZS1jb20iLCJhdWQiOiJvZmZsaW5lLXRva2VuLWdlbmVyYXRvciIsInN1YiI6IjVlYjZlYmMyLTJiNzgtNGFmNC1hNjJiLTkwZTBhODEwYTRhYiIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJvZmZsaW5lLXRva2VuLWdlbmVyYXRvciIsInNlc3Npb25fc3RhdGUiOiI3MWRlMDYzNC00YWYxLTQ4NTQtOGMyNC00MjY0YmE3N2M3OGMiLCJjbGllbnRfc2Vzc2lvbiI6ImNkOTA1YmM1LTkwMjctNDIyZS04YmUzLTgwOTliZjhjYWVlMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJ2aWV3LXByb2ZpbGUiXX19fQ.kgWNpsTtPsA4005yHhnyAFtqyCqaYgcRnaeL8POqjlCq6UnJfDTVKgA9EsgsRGNKMrXwv8TBzCmoC_0h57PK7Lc-zw3cKJ0E7IBQynSMPEZPw6bXfuimVhTtg3eNDO0xtar2Cs51rOTCQrfcudMaOedThmThuZ7A2PXJWZa1DooJwTWpecRHt9kibdrO9c8hI-iGqodRXII5OvX_RTSCO67ro6CTKXyf4uOfEojBej8x1A1xH8XRUs6LgwdVbNqQZp-XlLklu0ekGZIu7ENA8wUpDNNwrwlDBrYym-7uPrfsXKRZaxNu8TJY2OQxYpkeVN3FJS-5sNMMUEUMVZjL2w";
	protected String perfectoHost = "https://ibmgbs.perfectomobile.com/nexperience/perfectomobile/wd/hub";
}
